-- MySQL Script generated by MySQL Workbench
-- Tue Jun  5 17:09:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kalareissut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kalareissut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kalareissut` DEFAULT CHARACTER SET utf8 ;
USE `kalareissut` ;

-- -----------------------------------------------------
-- Table `kalareissut`.`tili`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kalareissut`.`tili` ;

CREATE TABLE IF NOT EXISTS `kalareissut`.`tili` (
  `idtili` INT NOT NULL AUTO_INCREMENT,
  `etunimi` VARCHAR(45) NOT NULL,
  `sukunimi` VARCHAR(45) NOT NULL,
  `kayttajatunnus` VARCHAR(255) NOT NULL,
  `salasana` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtili`),
  UNIQUE INDEX `ktunnus_UNIQUE` (`kayttajatunnus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kalareissut`.`reissu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kalareissut`.`reissu` ;

CREATE TABLE IF NOT EXISTS `kalareissut`.`reissu` (
  `idreissu` INT NOT NULL AUTO_INCREMENT,
  `pvm` DATE NOT NULL,
  `paikka` VARCHAR(45) NULL,
  `Saa` VARCHAR(45) NULL DEFAULT NULL,
  `t_nopeus` INT NULL DEFAULT NULL COMMENT 'Tuulen nopeus (m/s)',
  `t_suunta` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Tuulen suunta',
  `l_ilma` INT NULL DEFAULT NULL COMMENT 'Ilman lämpötila',
  `l_vesi` INT NULL DEFAULT NULL COMMENT 'Veden lämpötila',
  `tili_idtili` INT NOT NULL,
  PRIMARY KEY (`idreissu`, `tili_idtili`),
  UNIQUE INDEX `idreissu_UNIQUE` (`idreissu` ASC),
  INDEX `fk_reissu_tili_idx` (`tili_idtili` ASC),
  CONSTRAINT `fk_reissu_tili`
    FOREIGN KEY (`tili_idtili`)
    REFERENCES `kalareissut`.`tili` (`idtili`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kalareissut`.`kalalajit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kalareissut`.`kalalajit` ;

CREATE TABLE IF NOT EXISTS `kalareissut`.`kalalajit` (
  `idkalalajit` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkalalajit`),
  UNIQUE INDEX `idkalalajit_UNIQUE` (`idkalalajit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kalareissut`.`vieheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kalareissut`.`vieheet` ;

CREATE TABLE IF NOT EXISTS `kalareissut`.`vieheet` (
  `idvieheet` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(45) NOT NULL,
  `valmistaja` VARCHAR(45) NOT NULL,
  `tyyppi` VARCHAR(45) NOT NULL,
  `vari` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvieheet`),
  UNIQUE INDEX `idvieheet_UNIQUE` (`idvieheet` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kalareissut`.`kalat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kalareissut`.`kalat` ;

CREATE TABLE IF NOT EXISTS `kalareissut`.`kalat` (
  `idkalat` INT NOT NULL AUTO_INCREMENT,
  `laji` VARCHAR(45) NULL,
  `paino` INT NULL DEFAULT NULL,
  `pituus` INT NULL DEFAULT NULL,
  `Pyyntitapa` VARCHAR(45) NULL,
  `viehe` VARCHAR(45) NULL,
  `viehe_vari` VARCHAR(45) NULL,
  `saantiaika` TIME NULL DEFAULT NULL,
  `reissu_idreissu` INT NOT NULL,
  `reissu_tili_idtili` INT NOT NULL,
  PRIMARY KEY (`idkalat`, `reissu_idreissu`, `reissu_tili_idtili`),
  UNIQUE INDEX `idkalat_UNIQUE` (`idkalat` ASC),
  INDEX `fk_kalat_reissu_idx` (`reissu_idreissu` ASC, `reissu_tili_idtili` ASC),
  CONSTRAINT `fk_kalat_reissu1`
    FOREIGN KEY (`reissu_idreissu` , `reissu_tili_idtili`)
    REFERENCES `kalareissut`.`reissu` (`idreissu` , `tili_idtili`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
